spring:
  datasource:
    #platform: postgres
    driver-class-name : org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/seguridadempleados
    username: postgres
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql : false
    hibernate.ddl-auto : update
     
#Propiedades para JWT
app:
  jwt-secret: JWTSecretKey
  jwt-expiration-milliseconds: 604800000
  